import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

import { cn } from '@/lib/utils';
import { BaseLayout } from '@/src/components/layouts';

import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={cn('h-full antialiased', 'font-sans', geist.variable)}>
      <body className="min-h-screen bg-[#07090F]">
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
