import type { Metadata } from 'next';
import { Geist } from 'next/font/google';

import { cn } from '@/lib/utils';

import { BaseLayout } from '@/components/layouts';

import { dmSerifDisplayFont, interFont } from './fonts';
import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn(
        'antialiased',
        'font-sans',
        geist.variable,
        dmSerifDisplayFont.variable,
        interFont.variable,
      )}
    >
      <body>
        <BaseLayout>{children}</BaseLayout>
      </body>
    </html>
  );
}
